### PR TITLE
change deprecated selector

### PR DESCRIPTION
**Pull request by dirk-thomas**
This patch should get rid of the deprecation warning shown as of Atom version 1.13.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
The second commit gets rid of the deprecated `shadowRoot` usage.

**Comment by dirk-thomas** [comment]
@negipo It would be great if you could find some time to review, merge, and release this.

**Comment by dirk-thomas** [comment]
@negipo I would be happy to do the release for you if you would like to add me as a contributor to the repo. As an alternative I could fork the repo and release a new version from there?

**Comment by negipo** [comment]
@dirk-thomas 

I am so sorry to check this PR too late.
Actually I'm not using this package for now so that it might take some time to fix issues like this.
It sounds great that you will be a contributor to this repos. I have added you as a contributor.

Thank you to your contribute! I'll merge and publish this soon.

**Comment by dirk-thomas** [comment]
Thank you!

**Pull request merged**
